---
title: "KSCostGrapher: Graphing Tool for The Model of Knowledge Sharing (cost of knowledge transfer as a parameter)"
author: "Yon Kwon"
date: "8/28/2023"
output: html_document
---

# Grapher for Tzogos Sequel

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE) 
library(R.matlab)
library(tidyverse) # tibble (dataframe)
library(ggplot2) # Plot
library(ggrepel) # geom_text_repel
library(scales) # parse_format() function
library(viridis) # colormap
library(ggsci) # colormap
library(svglite) # print in *.svg format
```

## Data Import
```{r data_file, eval=FALSE}
# rm(list=c('data'))
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # Set SRC DIR as WD
file_data <- file.choose()
data <- readMat(file_data)
fig_id <- tools::file_path_sans_ext((basename(file_data)))
```

## User Config
```{r usr_config}
fig_width <- 6
fig_height <- 4
fig_dpi <- 600
fig_alpha <- .75
label_size <- 12
tick_label_size <- 10
legend_size <- 10
fig_open <- T # Open figure on R dev. env.
fig_save <- T # Save figure as *.svg

ci_alpha <- .99
ci_multiplier <- as.numeric(qnorm(ci_alpha) / sqrt(data$para.iteration))
```

## Figure 1. Knowledge Sharing * Seeking -> Performance
```{r fig1}
set_fig1_t <- data$para.time
# set_fig1_t <- 10
set_fig1_beta <- 1
set_fig1_cost <- 1

set_fig1_outcome <- data$r.know.avg[set_fig1_beta, set_fig1_cost, , , set_fig1_t]
set_fig1_outcome_label <- 'Firm Performance'

df_fig1 <- data.frame()
for( p1 in 1:data$para.l.p1 ){
  for( p2 in 1:data$para.l.p2 ){
    df_next <- data.frame(
      p1 = data$para.a.p1[p1],
      p2 = data$para.a.p2[p2],
      outcome = set_fig1_outcome[p1,p2]
    )
    df_fig1 <- rbind(df_fig1, df_next)
  }
}

fig1 <- ggplot(df_fig1, aes(x = p1, y = p2, fill = outcome)) +
  geom_tile(colour="white", size=0.25) +
  theme_grey(base_size=8)+
  #theme options
  theme_bw() +
  theme(
  #bold font for legend text
  legend.text=element_text(face="bold"),
  #set thickness of axis ticks
  axis.ticks=element_line(size=0.4),
  #remove plot background
  plot.background=element_blank(),
  #remove plot border
  panel.border=element_blank()
  )


fig1
```

## Figure 2. t * Knowledge Sharing * Seeking -> Performance
```{r fig2}
set_fig2_beta <- 1
set_fig2_cost <- 4

set_fig2_time_limit <- data$para.time
set_fig2_time <- 1:set_fig2_time_limit

set_fig2_p1 <- 1:data$para.l.p1
set_fig2_p2 <- 1:data$para.l.p2

# set_fig2_p1 <- c(2, 4, 6, 8)
# set_fig2_p2 <- c(2, 4, 6, 8)

set_fig2_outcome <- data$r.know.avg[set_fig2_beta, set_fig2_cost, , , set_fig2_time]
set_fig2_outcome_label <- 'Firm Performance'

# set_fig2_outcome <- data$r.cent.avg[set_fig2_beta, set_fig2_cost, , , set_fig2_time]
# set_fig2_outcome_label <- 'Centralization'

df_fig2 <- data.frame()
for( p1 in set_fig2_p1 ){
  for( p2 in set_fig2_p2 ){
    df_next <- data.frame(
      p1 = paste0('p[sharing]==',data$para.a.p1[p1]),
      p2 = paste0('p[seeking]==',data$para.a.p2[p2]),
      time= 1:data$para.time,
      outcome = set_fig2_outcome[p1,p2,]
    )
    df_fig2 <- rbind(df_fig2, df_next)
  }
}



fig2 <- ggplot(df_fig2, aes(x = time, y = outcome, linetype = p2, color = p1)) +
  geom_line() +
  scale_color_aaas(labels = parse_format()) +
  scale_linetype_discrete(labels = parse_format(), values = c(':','--','-')) +
  scale_x_continuous(expand = c(0, 0)) +
  xlab('Time Periods') +
  ylab(set_fig2_outcome_label) +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    legend.title = element_blank(),
    legend.box='vertical',
    legend.position = 'right'
  )

fig2

fig2_params_label <- paste0(
  'fig2',
  'b', data$para.a.b[set_fig2_beta],
  'c', data$para.a.c[set_fig2_cost],
  'p1', paste0(set_fig2_p1, collapse = ","),
  'p2', paste0(set_fig2_p2, collapse = ","),
  'res_', set_fig2_outcome_label
)

ggsave(
  paste0(fig_id, '_', fig2_params_label, '.png'),
  plot = fig2,
  units = 'in', 
  width = 6,
  height = 3,
  dpi = fig_dpi
)
```