---
title: "KSDyadicGrapher: Graphing Tool for The Model of Knowledge Sharing (as dyadic knowledge transfer)"
author: "Yon Kwon"
date: "8/28/2023"
output: html_document
---

# Grapher for Tzogos Sequel

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE) 
library(R.matlab)
library(tidyverse) # tibble (dataframe)
library(ggplot2) # Plot
library(ggrepel) # geom_text_repel
library(scales) # parse_format() function
library(viridis) # colormap
library(ggsci) # colormap
library(svglite) # print in *.svg format
```

## Data Import
```{r data_file, eval=FALSE}
# rm(list=c('data'))
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # Set SRC DIR as WD
file_data <- file.choose()
data <- readMat(file_data)
fig_id <- tools::file_path_sans_ext((basename(file_data)))
```

## User Config
```{r usr_config}
fig_width <- 6
fig_height <- 4
fig_dpi <- 600
fig_alpha <- .75
label_size <- 12
tick_label_size <- 10
legend_size <- 10
fig_open <- T # Open figure on R dev. env.
fig_save <- T # Save figure as *.svg

ci_alpha <- .99
ci_multiplier <- as.numeric(qnorm(ci_alpha) / sqrt(data$para.iteration))
```

## Figure 0. beta to efficiency
```{r fig0}
df_fig0 <- data.frame(
  beta = t(data$para.a.b),
  efficiency = data$r.effi.avg[,1,1]
)

fig0 <- ggplot(df_fig0, aes(x = beta, y = efficiency)) +
  geom_line() +
  xlab('beta (Structural Integration)') +
  ylab('Efficiency of Org. Design') +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    legend.title = element_blank(),
    legend.box='vertical',
    legend.position = 'right'
  )

fig0

fig0_params_label <- paste0(
  'fig0'
)

ggsave(
  paste0(fig_id, '_', fig0_params_label, '.png'),
  plot = fig0,
  units = 'in', 
  width = 4,
  height = 2,
  dpi = fig_dpi
)
```

## Figure 1. t * Knowledge Sharing -> Performance @ average beta
```{r fig1}
set_fig1_p.s <- 1:data$para.l.p.s
set_fig1_p.s <- c(1, 6, 11)
set_fig1_time_limit <- data$para.time
set_fig1_time <- 1:set_fig1_time_limit

# set_fig1_outcome <- data$r.know.avg[set_fig1_beta, , set_fig1_time]
set_fig1_outcome <- data$r.know.avg[, , set_fig1_time]
set_fig1_outcome_label <- 'Firm Performance'

# set_fig1_outcome <- data$r.cent.avg[, , set_fig1_time]
# set_fig1_outcome_label <- 'Centralization'

df_fig1 <- data.frame()
for( p.s in set_fig1_p.s ){
  df_next <- data.frame(
    p.s = paste0('p[sharing]==',data$para.a.p.s[p.s]),
    time= 1:data$para.time,
    # outcome = set_fig1_outcome[p.s,]
    outcome = apply(set_fig1_outcome[,p.s,], MARGIN=2, FUN=mean)
  )
  df_fig1 <- rbind(df_fig1, df_next)
}



fig1 <- ggplot(df_fig1, aes(x = time, y = outcome, color = p.s)) +
  geom_line() +
  scale_color_npg(labels = parse_format()) +
  scale_linetype_manual(labels = parse_format(), values = c('dotted','dashed','solid')) +
  scale_x_continuous(expand = c(0, 0)) +
  xlab('Time Periods') +
  ylab(set_fig1_outcome_label) +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    legend.title = element_blank(),
    legend.box='vertical',
    legend.position = 'right'
  )

fig1

fig1_params_label <- paste0(
  'fig1',
  'p.s', paste0(set_fig1_p.s, collapse = ","),
  'res_', set_fig1_outcome_label
)

ggsave(
  paste0(fig_id, '_', fig1_params_label, '.png'),
  plot = fig1,
  units = 'in', 
  width = 4,
  height = 2,
  dpi = fig_dpi
)
```


## Figure 2. t * Knowledge Sharing -> Performance @ beta
```{r fig2}
set_fig2_beta <- 1
set_fig2_p.s <- 1:data$para.l.p.s
set_fig2_p.s <- c(1, 6, 11)
set_fig2_time_limit <- data$para.time
set_fig2_time <- 1:set_fig2_time_limit

set_fig2_outcome <- data$r.know.avg[set_fig2_beta, , set_fig2_time]
set_fig2_outcome_label <- 'Firm Performance'

# set_fig2_outcome <- data$r.cent.avg[set_fig2_beta, set_fig2_epsilon, , , set_fig2_time]
# set_fig2_outcome_label <- 'Centralization'

df_fig2 <- data.frame()
for( p.s in set_fig2_p.s ){
  df_next <- data.frame(
    p.s = paste0('p[sharing]==',data$para.a.p.s[p.s]),
    time= 1:data$para.time,
    outcome = set_fig2_outcome[p.s,]
  )
  df_fig2 <- rbind(df_fig2, df_next)
}



fig2 <- ggplot(df_fig2, aes(x = time, y = outcome, color = p.s)) +
  geom_line() +
  scale_color_npg(labels = parse_format()) +
  scale_linetype_manual(labels = parse_format(), values = c('dotted','dashed','solid')) +
  scale_x_continuous(expand = c(0, 0)) +
  xlab('Time Periods') +
  ylab(set_fig2_outcome_label) +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    legend.title = element_blank(),
    legend.box='vertical',
    legend.position = 'right'
  )

fig2

fig2_params_label <- paste0(
  'fig2',
  'b', data$para.a.b[set_fig2_beta],
  'p.s', paste0(set_fig2_p.s, collapse = ","),
  'res_', set_fig2_outcome_label
)

ggsave(
  paste0(fig_id, '_', fig2_params_label, '.png'),
  plot = fig2,
  units = 'in', 
  width = 4,
  height = 2,
  dpi = fig_dpi
)
```

## Figure 3. beta * Knowledge Sharing -> Performance @ t
```{r fig3}
set_fig3_beta <- 1:data$para.l.b
set_fig3_p.s <- c(1, 6, 11)
set_fig3_time <- data$para.time

set_fig3_outcome <- data$r.know.avg[set_fig3_beta, , set_fig3_time]
set_fig3_outcome_label <- 'Firm Performance'

# set_fig3_outcome <- data$r.cent.avg[set_fig3_beta, , set_fig3_time]
# set_fig3_outcome_label <- 'Centralization'

df_fig3 <- data.frame()
for( p.s in set_fig3_p.s ){
  df_next <- data.frame(
    beta = data$para.a.b[set_fig3_beta],
    p.s = paste0('p[sharing]==',data$para.a.p.s[,p.s]),
    outcome = set_fig3_outcome[,p.s]
  )
  df_fig3 <- rbind(df_fig3, df_next)
}

fig3 <- ggplot(df_fig3, aes(x = beta, y = outcome, color = p.s)) +
  geom_line() +
  scale_color_npg(labels = parse_format()) +
  scale_linetype_manual(labels = parse_format(), values = c('dotted','dashed','solid')) +
  scale_x_continuous(expand = c(0, 0)) +
  xlab('Structural Integration (Beta)') +
  ylab(set_fig3_outcome_label) +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    legend.title = element_blank(),
    legend.box='vertical',
    legend.position = 'right'
  )

fig3

fig3_params_label <- paste0(
  'fig3',
  'p.s', paste0(set_fig3_p.s, collapse = ","),
  'time', set_fig3_time,
  'res_', set_fig3_outcome_label
)

ggsave(
  paste0(fig_id, '_', fig3_params_label, '.png'),
  plot = fig3,
  units = 'in', 
  width = 4,
  height = 2,
  dpi = fig_dpi
)
```

## Figure 4. Knowledge Sharing -> Optimal Beta @ t
```{r fig4}
set_fig4_beta <- 1:data$para.l.b
set_fig4_p.s <- c(1, 6, 11)
set_fig4_p.s <- c(1, 3, 5, 7, 9, 10, 11)
set_fig4_time <- data$para.time

set_fig4_outcome <- data$r.know.avg[set_fig4_beta, , set_fig4_time]
set_fig4_outcome_label <- 'Firm Performance'

# set_fig4_outcome <- data$r.cent.avg[set_fig4_beta, set_fig4_epsilon, , , set_fig4_time]
# set_fig4_outcome_label <- 'Centralization'

df_fig4 <- data.frame()
for( p.s in set_fig4_p.s ){
  df_next <- data.frame(
    beta = data$para.a.b[set_fig4_beta],
    p.s = paste0('p[sharing]==',data$para.a.p.s[,p.s]),
    outcome = set_fig4_outcome[,p.s]
  )
  df_fig4 <- rbind(df_fig4, df_next)
}

df_fig4_optimal <- data.frame()
for( p.s in set_fig4_p.s ){
  max_index <- which.max(set_fig4_outcome[,p.s])
  df_next <- data.frame(
    p.s = paste0('p[sharing]==',data$para.a.p.s[,p.s]),
    beta = data$para.a.b[max_index],
    outcome = set_fig4_outcome[max_index,p.s]
  )
  df_fig4_optimal <- rbind(df_fig4_optimal, df_next)
}

fig4 <- ggplot(df_fig4, aes(x = beta, y = outcome, color = p.s)) +
  geom_line() +
  geom_point(df_fig4_optimal, mapping = aes(x=beta, y=outcome), shape='*', size = 5) +
  scale_color_npg(labels = parse_format()) +
  scale_linetype_manual(labels = parse_format(), values = c('dotted','dashed','solid')) +
  scale_x_continuous(expand = c(0, 0)) +
  xlab('Structural Integration (Beta)') +
  ylab(set_fig4_outcome_label) +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    legend.title = element_blank(),
    legend.box='vertical',
    legend.position = 'right'
  )

fig4

fig4_params_label <- paste0(
  'fig4',
  'p.s', paste0(set_fig4_p.s, collapse = ","),
  'time', set_fig4_time,
  'res_', set_fig4_outcome_label
)

ggsave(
  paste0(fig_id, '_', fig4_params_label, '.png'),
  plot = fig4,
  units = 'in', 
  width = 4,
  height = 2,
  dpi = fig_dpi
)
```